apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb-infra
  namespace: metallb
resources:
  # IMPORTANT: Apply CRDs Kustomization first
  - ./crds
  - metallb.yaml