apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-values
  namespace: harbor
data:
  # Content of your values.yaml goes here, indented
  values.yaml: |
    expose:
      type: loadBalancer
      tls:
        enabled: true
        certSource: secret
        auto:
          commonName: ""
        secret:
          secretName: "harbor-cert"
          notarySecretName: "harbor-cert"
      ingress:
        hosts:
          core: harbor.mydomain.com
          notary: harbor.mydomain.com
    externalURL: https://harbor.mydomain.com
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
    harborAdminPassword: "dms"