apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert # Name of the Certificate resource
  namespace: harbor # Must be in the same namespace as Harbor
spec:
  secretName: harbor-cert
  dnsNames:
    - hub.dms.in
  issuerRef:
    name: none
    kind: Issuer