apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-values
  namespace: harbor
data:
  values.yaml: |
    expose:
      type: ClusterIP
      tls:
        enabled: true
      ingress:
        enabled: true
        hosts:
          core: flux.local.external.local.gardener.cloud
    externalURL: https://harbor.dms.com 
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
    harborAdminPassword: "dms"
    nginx:
      enabled: true 
      tls:
        enabled: false
