apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-values
  namespace: harbor
data:
  values.yaml: |
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: "harbor-cert"
          notarySecretName: "harbor-cert"
      ingress:
        hosts:
          core: hub.dms.in
          notary: notary.dms.in
        className: nginx
    externalURL: https://hub.dms.in
    internalTLS:
      enabled: true
      certSource: "auto"
    logLevel: info
    #existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
    harborAdminPassword: "demo"
    portal:
      replicas: 1
    core:
      replicas: 1
    jobservice:
      replicas: 1
    registry:
      replicas: 1
    trivy:
      replicas: 1
    notary:
      enabled: true
      server:
        replicas: 1
      signer:
        replicas: 1
    database:
      type: internal
    redis:
      type: internal
    exporter:
      replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    trace:
      enabled: false
    cache:
      enabled: true
