apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-values
  namespace: harbor
data:
  # Content of your values.yaml goes here, indented
  values.yaml: |
    expose:
      type: ClusterIP 
      tls:
        enabled: true
        certSource: secret
        secretName: harbor-cert 
      ingress:
        enabled: true # Enable Ingress
        hosts:
          core: flux.local.external.local.gardener.cloud 
    externalURL: https://harbor.dms.com
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
    harborAdminPassword: "dms"