apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-values
  namespace: harbor
data:
  values.yaml: |
    expose:
      type: ingress
      tls:
        enabled: false
      ingress:
        hosts:
          core: hub.dms.in
          notary: notary.hub.dms.in
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
    externalURL: http://hub.dms.in
    internalTLS:
      enabled: false
    logLevel: info
    harborAdminPassword: "demo"
    portal:
      replicas: 1
    core:
      replicas: 1
    jobservice:
      replicas: 1
    registry:
      replicas: 1
    trivy:
      replicas: 1
    notary:
      enabled: true
      server:
        replicas: 1
      signer:
        replicas: 1
    database:
      type: internal
    redis:
      type: internal
    exporter:
      replicas: 1
    trace:
      enabled: false
    cache:
      enabled: true
