apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "1.14.x"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      remediateLastFailure: true
    timeout: 10m
  upgrade:
    remediation:
      remediateLastFailure: true
      strategy: rollback
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: harbor-values-configmap
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    expose:
      tls:
        enabled: true
        certSource: secret
        secretName: harbor-cert
