# Add/modify these sections in your existing apps/harbor/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "1.17.x" # Your desired Harbor version
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      remediateLastFailure: true
    timeout: 10m # Ensure this is increased
  upgrade:
    remediation:
      remediateLastFailure: true
      strategy: rollback
    timeout: 10m # Ensure this is increased
  valuesFrom:
    - kind: ConfigMap
      name: harbor-values
  # IMPORTANT: Dependency on cert-manager HelmRelease
  dependsOn:
    - name: cert-manager

