apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: harbor-apps
  namespace: harbor
resources:
  - helm-release.yaml
  - harbor-values-configmap.yaml # If you use it
  - harbor-certificate.yaml # <-- Ensure this line is present
