apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: harbor-apps
  namespace: harbor
resources:
  - namespace.yaml
  - harbor-helm-repository.yaml
  - harbor-values-configmap.yaml
  - helm-release.yaml
