---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    toolkit.fluxcd.io/tenant: gardener-demo
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager # Flux will create this namespace if it doesn't exist
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.14.x" # Keep this version for Kubernetes 1.32.x compatibility
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
      strategy: rollback
  # IMPORTANT: Remove this line as CRDs are managed separately now
  # installCRDs: true
  values:
    # Optional: adjust resource limits if your local Kind node is still resource constrained
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  # NEW: Add a dependency on the CRDs Kustomization
  dependsOn:
    - name: cert-manager-crds # This refers to the Kustomization for CRDs
      namespace: flux-system # Assuming the root Kustomization in flux-system reconciles the infra/cert-manager Kustomization