apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager # Flux will create this namespace if it doesn't exist
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.14.x" # Compatible with Kubernetes 1.32.x
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
      strategy: rollback
  values:
    installCRDs: true # This is crucial for cert-manager to work
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
