apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-infra
  namespace: cert-manager
resources:
  - cert-manager-helm-repository.yaml
  - cert-manager-helm-release.yaml
  - cert-manager-issuer.yaml
