apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: infrastructure
resources:
  # IMPORTANT: Only include ingress now
  - ./ingress
  - ./metallb