apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: infrastructure
resources:
  # IMPORTANT: Ensure cert-manager resources are listed before apps that depend on them
  - ./cert-manager
  - ./ingress